from bash.bash import Bash
from core.alphabet import Alphabet
from core.nav import Navigation
from core.numbers import Numbers
from core.punctuation import Punctuation
from cpp.cpp import CPP
from csharp.csharp import CSharp
from haxe.haxe import Haxe
from html.html import HTML
from java.java import Java
from javascript.javascript import Javascript
from python.python import Python
from rust.rust import Rust
from sql.sql import SQL